# Generated by Django 4.2.4 on 2023-08-03 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time",
            new_name="estimated_time",
        ),
    ]
