# Generated by Django 4.2.4 on 2023-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_time_recipe_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "g"),
                    ("kg", "kg"),
                    ("l", "l"),
                    ("ml", "ml"),
                    ("unit", "unit"),
                ],
                max_length=10,
            ),
        ),
    ]
