version: '3.8'

services:
  fresco-api:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fresco
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
