version: '3.8'

services:
  fresco-api:
    build: .
    restart: always
    ports:
      - 8000:8000

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    expose:
      - "5432"
    environment:
      DOCKER_DEFAULT_PLATFORM: linux/amd64
      POSTGRES_PASSWORD: sergio
      POSTGRES_USER: postgres
      POSTGRES_DB: fresco
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "120:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: aaa
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
